CREATE TABLE IF NOT EXISTS roadtrips (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  owner_id   INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name       VARCHAR(200) NOT NULL,
  date       DATE NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS roadtrip_members (
  roadtrip_id INT NOT NULL REFERENCES roadtrips(id) ON DELETE CASCADE,
  user_id     INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (roadtrip_id, user_id)
);

CREATE TABLE IF NOT EXISTS roadtrip_todos (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  roadtrip_id INT NOT NULL REFERENCES roadtrips(id) ON DELETE CASCADE,
  text        VARCHAR(500) NOT NULL,
  done        TINYINT(1) NOT NULL DEFAULT 0,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
